name: ci
on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: latest

      - name: Check format
        run: deno fmt --check

      - name: Check lint
        run: deno lint

      - name: Run tests
        run: deno task test
